### ISSUE TITLE
 missing requirement [...] osgi.wiring.package

### ISSUE THREAD

**Issue by Pentadactylus** [sonatype-nexus-community/nexus-repository-r#23]
I'm trying to install this plugin from the Nexus shell, but when it comes to starting the jar, I'm always getting an error:

```
2018-01-26 12:23:54,011+0100 ERROR [Karaf local console user karaf] *SYSTEM org.apache.karaf.shell.support.ShellUtil - Exception caught while executing command
org.apache.karaf.shell.support.MultiException: Error executing command on bundles:
        Error starting bundle 248: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-r [248](R 248.0): missing requirement [org.sonatype.nexus.plugins.nexus-repository-r [248](R 248.0)] osgi.wiring.package; (&(osgi.wiring.package=org.sonatype.nexus.blobstore.api)(version>=3.5.0)) Unresolved requirements: [[org.sonatype.nexus.plugins.nexus-repository-r [248](R 248.0)] osgi.wiring.package; (&(osgi.wiring.package=org.sonatype.nexus.blobstore.api)(version>=3.5.0))]
        at org.apache.karaf.shell.support.MultiException.throwIf(MultiException.java:61) [na:na]
        at org.apache.karaf.bundle.command.BundlesCommand.doExecute(BundlesCommand.java:69) [na:na]
        at org.apache.karaf.bundle.command.BundlesCommand.execute(BundlesCommand.java:54) [na:na]
        at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:83) [na:na]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:67) [na:na]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:87) [na:na]
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480) [na:na]
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406) [na:na]
        at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108) [na:na]
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182) [na:na]
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119) [na:na]
        at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:94) [na:na]
        at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.run(ConsoleSessionImpl.java:274) [na:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
        Suppressed: java.lang.Exception: Error starting bundle 248: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-r [248](R 248.0): missing requirement [org.sonatype.nexus.plugins.nexus-repository-r [248](R 248.0)] osgi.wiring.package; (&(osgi.wiring.package=org.sonatype.nexus.blobstore.api)(version>=3.5.0)) Unresolved requirements: [[org.sonatype.nexus.plugins.nexus-repository-r [248](R 248.0)] osgi.wiring.package; (&(osgi.wiring.package=org.sonatype.nexus.blobstore.api)(version>=3.5.0))]
                at org.apache.karaf.bundle.command.BundlesCommand.doExecute(BundlesCommand.java:66) [na:na]
                ... 12 common frames omitted
        Caused by: org.osgi.framework.BundleException: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-r [248](R 248.0): missing requirement [org.sonatype.nexus.plugins.nexus-repository-r [248](R 248.0)] osgi.wiring.package; (&(osgi.wiring.package=org.sonatype.nexus.blobstore.api)(version>=3.5.0)) Unresolved requirements: [[org.sonatype.nexus.plugins.nexus-repository-r [248](R 248.0)] osgi.wiring.package; (&(osgi.wiring.package=org.sonatype.nexus.blobstore.api)(version>=3.5.0))]
                at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
                at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
                at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
                at org.apache.karaf.bundle.command.Start.executeOnBundle(Start.java:38)
                at org.apache.karaf.bundle.command.BundlesCommand.doExecute(BundlesCommand.java:64)
                ... 12 common frames omitted
Error executing command: Error executing command on bundles:
        Error starting bundle 248: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-r [248](R 248.0): missing requirement [org.sonatype.nexus.plugins.nexus-repository-r [248](R 248.0)] osgi.wiring.package; (&(osgi.wiring.package=org.sonatype.nexus.blobstore.api)(version>=3.5.0)) Unresolved requirements: [[org.sonatype.nexus.plugins.nexus-repository-r [248](R 248.0)] osgi.wiring.package; (&(osgi.wiring.package=org.sonatype.nexus.blobstore.api)(version>=3.5.0))]
```
I have checked that file org.osgi.core-6.0.0.jar is present within the lib/boot directory and I even installed it explicitly over the nexus shell, but I'm still getting the error when I'm running bundle:run <id>.

My server is not directly connected to the internet, but I have set a proxy (for mvn when I built the package, and also for Nexus). This could pose a problem, but I don't see the reason how.

Do you have any hint what could be wrong with my setup?

**Comment by shrewdraven** [comment]
Did you get a solution for this error? I am getting a similar one.

**Comment by joedragons** [comment]
I didn't have any issue on NXRM3.12-SNAPSHOT when I tried today.  What NXRM3 version are you trying against?  Are you using 1.1?

**Comment by Pentadactylus** [comment]
I have given up on Nexus in the end cause it didn't meet my expectations - and no, I didn't find a solution for this problem.
