### ISSUE TITLE
Error on Nexus Repository Pro v3.14.0-04

### ISSUE THREAD

**Issue by chandan4747** [sonatype-nexus-community/nexus-repository-r#43]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Currently we have Nexus Repository Manager v3.13.0 and nexus-repository-r plugin with v1.0.1 running. 
Further to upgrading to Nexus Repository Manager 3.14.0-04 version, we had placed the plugin under the newly installed version and updated the relevant config files.

* **What feature or behavior is this required for?**
We have currently configured some R repositories on Nexus 3.13.0 and was expecting the same behavior further to upgrading to Nexus 3.14.0.

* **How could we solve this issue? (Not knowing is okay!)**
We are currently getting the below error message:

2018-10-23 15:38:45,746-0400 INFO  [jetty-main-1]  *SYSTEM org.sonatype.nexus.extender.NexusLifecycleManager - Start KERNEL
2018-10-23 15:38:45,748-0400 INFO  [jetty-main-1]  *SYSTEM org.sonatype.nexus.internal.log.LogbackLoggerOverrides - File: /binrepo/nexus/nexus-work3/nexus3/etc/logback/logback-overrides.xml
2018-10-23 15:38:45,750-0400 INFO  [jetty-main-1]  *SYSTEM org.sonatype.nexus.internal.log.LogbackLogManager - Configuring
2018-10-23 15:38:45,765-0400 INFO  [jetty-main-1]  *SYSTEM org.sonatype.nexus.extender.NexusContextListener - Installing: [nexus-pro-feature/3.14.0.04]
2018-10-23 15:38:47,655-0400 ERROR [jetty-main-1]  *SYSTEM org.sonatype.nexus.extender.NexusContextListener - Failed to initialize context
org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-pro-feature; type=karaf.feature; version="[3.14.0.04,3.14.0.04]"; filter:="(&(osgi.identity=nexus-pro-feature)(type=karaf.feature)(version>=3.14.0.04)(version<=3.14.0.04))" [caused by: Unable to resolve nexus-pro-feature/3.14.0.04: missing requirement [nexus-pro-feature/3.14.0.04] osgi.identity; osgi.identity=nexus-repository-r; type=karaf.feature; version="[1.0.1,1.0.1]" [caused by: Unable to resolve nexus-repository-r/1.0.1: missing requirement [nexus-repository-r/1.0.1] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-repository-r; type=osgi.bundle; version="[1.0.1,1.0.1]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-r/1.0.1: missing requirement [org.sonatype.nexus.plugins.nexus-repository-r/1.0.1] osgi.wiring.package; filter:="(osgi.wiring.package=se.sawano.java.text)"]]]
	at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:389)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:347)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:216)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-10-23 15:38:47,657-0400 ERROR [jetty-main-1]  *SYSTEM org.sonatype.nexus.bootstrap.osgi.BootstrapListener - Failed to initialize
java.lang.RuntimeException: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-pro-feature; type=karaf.feature; version="[3.14.0.04,3.14.0.04]"; filter:="(&(osgi.identity=nexus-pro-feature)(type=karaf.feature)(version>=3.14.0.04)(version<=3.14.0.04))" [caused by: Unable to resolve nexus-pro-feature/3.14.0.04: missing requirement [nexus-pro-feature/3.14.0.04] osgi.identity; osgi.identity=nexus-repository-r; type=karaf.feature; version="[1.0.1,1.0.1]" [caused by: Unable to resolve nexus-repository-r/1.0.1: missing requirement [nexus-repository-r/1.0.1] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-repository-r; type=osgi.bundle; version="[1.0.1,1.0.1]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-r/1.0.1: missing requirement [org.sonatype.nexus.plugins.nexus-repository-r/1.0.1] osgi.wiring.package; filter:="(osgi.wiring.package=se.sawano.java.text)"]]]
	at org.sonatype.nexus.extender.NexusContextListener.contextInitialized(NexusContextListener.java:181)
	at org.sonatype.nexus.bootstrap.osgi.ListenerTracker.addingService(ListenerTracker.java:47)
	at org.sonatype.nexus.bootstrap.osgi.ListenerTracker.addingService(ListenerTracker.java:1)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261)
	at org.sonatype.nexus.bootstrap.osgi.BootstrapListener.contextInitialized(BootstrapListener.java:121)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:953)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:558)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:918)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:370)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:848)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:92)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:419)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:386)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.sonatype.nexus.bootstrap.jetty.JettyServer$JettyMainThread.run(JettyServer.java:274)
Caused by: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-pro-feature; type=karaf.feature; version="[3.14.0.04,3.14.0.04]"; filter:="(&(osgi.identity=nexus-pro-feature)(type=karaf.feature)(version>=3.14.0.04)(version<=3.14.0.04))" [caused by: Unable to resolve nexus-pro-feature/3.14.0.04: missing requirement [nexus-pro-feature/3.14.0.04] osgi.identity; osgi.identity=nexus-repository-r; type=karaf.feature; version="[1.0.1,1.0.1]" [caused by: Unable to resolve nexus-repository-r/1.0.1: missing requirement [nexus-repository-r/1.0.1] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-repository-r; type=osgi.bundle; version="[1.0.1,1.0.1]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-r/1.0.1: missing requirement [org.sonatype.nexus.plugins.nexus-repository-r/1.0.1] osgi.wiring.package; filter:="(osgi.wiring.package=se.sawano.java.text)"]]]
	at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:389)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:347)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:216)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-10-23 15:38:47,657-0400 WARN  [jetty-main-1]  *SYSTEM org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@6595d05f{Sonatype Nexus,/repo,file:///trvapps/nexus/nexus-3.14.0-04/public/,UNAVAILABLE}
java.lang.RuntimeException: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-pro-feature; type=karaf.feature; version="[3.14.0.04,3.14.0.04]"; filter:="(&(osgi.identity=nexus-pro-feature)(type=karaf.feature)(version>=3.14.0.04)(version<=3.14.0.04))" [caused by: Unable to resolve nexus-pro-feature/3.14.0.04: missing requirement [nexus-pro-feature/3.14.0.04] osgi.identity; osgi.identity=nexus-repository-r; type=karaf.feature; version="[1.0.1,1.0.1]" [caused by: Unable to resolve nexus-repository-r/1.0.1: missing requirement [nexus-repository-r/1.0.1] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-repository-r; type=osgi.bundle; version="[1.0.1,1.0.1]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-r/1.0.1: missing requirement [org.sonatype.nexus.plugins.nexus-repository-r/1.0.1] osgi.wiring.package; filter:="(osgi.wiring.package=se.sawano.java.text)"]]]
	at org.sonatype.nexus.extender.NexusContextListener.contextInitialized(NexusContextListener.java:181)
	at org.sonatype.nexus.bootstrap.osgi.ListenerTracker.addingService(ListenerTracker.java:47)
	at org.sonatype.nexus.bootstrap.osgi.ListenerTracker.addingService(ListenerTracker.java:1)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261)
	at org.sonatype.nexus.bootstrap.osgi.BootstrapListener.contextInitialized(BootstrapListener.java:121)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:953)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:558)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:918)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:370)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:848)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:92)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:419)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:386)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.sonatype.nexus.bootstrap.jetty.JettyServer$JettyMainThread.run(JettyServer.java:274)
Caused by: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-pro-feature; type=karaf.feature; version="[3.14.0.04,3.14.0.04]"; filter:="(&(osgi.identity=nexus-pro-feature)(type=karaf.feature)(version>=3.14.0.04)(version<=3.14.0.04))" [caused by: Unable to resolve nexus-pro-feature/3.14.0.04: missing requirement [nexus-pro-feature/3.14.0.04] osgi.identity; osgi.identity=nexus-repository-r; type=karaf.feature; version="[1.0.1,1.0.1]" [caused by: Unable to resolve nexus-repository-r/1.0.1: missing requirement [nexus-repository-r/1.0.1] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-repository-r; type=osgi.bundle; version="[1.0.1,1.0.1]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-r/1.0.1: missing requirement [org.sonatype.nexus.plugins.nexus-repository-r/1.0.1] osgi.wiring.package; filter:="(osgi.wiring.package=se.sawano.java.text)"]]]
	at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:389)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:347)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:216)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-10-23 15:38:47,667-0400 INFO  [jetty-main-1]  *SYSTEM org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@65a59315{HTTP/1.1,[http/1.1]}{10.48.5.255:8080}
2018-10-23 15:38:47,667-0400 ERROR [jetty-main-1]  *SYSTEM org.sonatype.nexus.bootstrap.jetty.JettyServer - Failed to start
java.lang.RuntimeException: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-pro-feature; type=karaf.feature; version="[3.14.0.04,3.14.0.04]"; filter:="(&(osgi.identity=nexus-pro-feature)(type=karaf.feature)(version>=3.14.0.04)(version<=3.14.0.04))" [caused by: Unable to resolve nexus-pro-feature/3.14.0.04: missing requirement [nexus-pro-feature/3.14.0.04] osgi.identity; osgi.identity=nexus-repository-r; type=karaf.feature; version="[1.0.1,1.0.1]" [caused by: Unable to resolve nexus-repository-r/1.0.1: missing requirement [nexus-repository-r/1.0.1] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-repository-r; type=osgi.bundle; version="[1.0.1,1.0.1]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-r/1.0.1: missing requirement [org.sonatype.nexus.plugins.nexus-repository-r/1.0.1] osgi.wiring.package; filter:="(osgi.wiring.package=se.sawano.java.text)"]]]
	at org.sonatype.nexus.extender.NexusContextListener.contextInitialized(NexusContextListener.java:181)
	at org.sonatype.nexus.bootstrap.osgi.ListenerTracker.addingService(ListenerTracker.java:47)
	at org.sonatype.nexus.bootstrap.osgi.ListenerTracker.addingService(ListenerTracker.java:1)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261)
	at org.sonatype.nexus.bootstrap.osgi.BootstrapListener.contextInitialized(BootstrapListener.java:121)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:953)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:558)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:918)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:370)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:848)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:92)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:419)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:386)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.sonatype.nexus.bootstrap.jetty.JettyServer$JettyMainThread.run(JettyServer.java:274)
Caused by: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-pro-feature; type=karaf.feature; version="[3.14.0.04,3.14.0.04]"; filter:="(&(osgi.identity=nexus-pro-feature)(type=karaf.feature)(version>=3.14.0.04)(version<=3.14.0.04))" [caused by: Unable to resolve nexus-pro-feature/3.14.0.04: missing requirement [nexus-pro-feature/3.14.0.04] osgi.identity; osgi.identity=nexus-repository-r; type=karaf.feature; version="[1.0.1,1.0.1]" [caused by: Unable to resolve nexus-repository-r/1.0.1: missing requirement [nexus-repository-r/1.0.1] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-repository-r; type=osgi.bundle; version="[1.0.1,1.0.1]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-r/1.0.1: missing requirement [org.sonatype.nexus.plugins.nexus-repository-r/1.0.1] osgi.wiring.package; filter:="(osgi.wiring.package=se.sawano.java.text)"]]]
	at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:389)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:347)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:216)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-10-23 15:38:47,702-0400 INFO  [FelixStartLevel]  *SYSTEM org.sonatype.nexus.extender.NexusContextListener - Uptime: 8 seconds and 146 milliseconds (nexus-pro-edition/3.14.0.04)
2018-10-23 15:38:47,704-0400 INFO  [FelixStartLevel]  *SYSTEM org.sonatype.nexus.extender.NexusLifecycleManager - Stop KERNEL

* **Anything else?**
List of changes done, further to upgrading to Nexus 3.14.0

- Copied nexus-repository-r-1.0.0.jar under <nexus_install_location>/system/org/sonatype/nexus/plugins/nexus-repository-r folder
  [The above jar file was copied from the previous Nexus Repository Instance]

	+-- nexus-repository-r
¦   +-- 1.0.0
¦       +-- nexus-repository-r-1.0.0.jar

- Updated <nexus_install_location>/system/com/sonatype/nexus/assemblies/nexus-pro-feature/3.14.0-04/nexus-pro-feature-3.14.0-features.xml file with the following
		
			  <feature version="3.x.y.xy" prerequisite="false" dependency="false">nexus-repository-rubygems</feature>
			+	  
			+     <feature version="1.0.1" prerequisite="false" dependency="false">nexus-repository-r</feature>
				  <feature version="3.x.y.xy" prerequisite="false" dependency="false">nexus-repository-yum</feature>
			  </feature>
			
			And

			
		<feature name="nexus-repository-r" description="org.sonatype.nexus.plugins:nexus-repository-r" version="1.0.1">
		  <details>org.sonatype.nexus.plugins:nexus-repository-r</details>
		  <bundle>mvn:org.sonatype.nexus.plugins/nexus-repository-r/1.0.1</bundle>
		</feature>
	 </features>

**Comment by doddi** [comment]
@chandan4747 It looks to me like you had previously used version 1.0.1 but you are now copying in an older version of 1.0.0

**Comment by russoz** [comment]
@doddi @chandan4747 Actually we had the same error happening, in a 3.14 installation using plugin 1.0.1. We never used v1.0.0 here.

I see commit 51696608f206ae64ee3fc1e4c03dd7be7aaf16c8 adding "se.sawano.java [...] since it was removed from nexus". Hope that does the trick.

**Comment by russoz** [comment]
No luck there, still getting the same error.

**Comment by DarthHater** [comment]
Go ahead and give #44 a shot y'all. There might be one more thing we need to do, but that's a branch that is updated to use 3.14.0-04.
